name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Change to backend directory
        run: cd backend
      - name: Build with Maven
        run: cd backend && mvn --batch-mode verify
      - name: Run tests
        run: cd backend && mvn test
